version: "3.9"
services:
  fasten-prod:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    hostname: ${HOST_HOSTNAME}
    environment:
      - HOST_IP=${HOST_IP}
    ports:
      - "9090:8080"
    volumes:
      - ./db:/opt/fasten/db
      - ./cache:/opt/fasten/cache