version: "3.9"
services:
  fasten-prod:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    hostname: ${HOSTNAME}
    environment:
      - HOST_IP=${IP}
      - HOST_PORT=${PORT}
    ports:
      - "${PORT}:8080"
    volumes:
      - ./db:/opt/fasten/db
      - ./cache:/opt/fasten/cache