name: Provider Request
description: Request a new institution/clinic/insurance provider to be added to Fasten
title: "[Provider Request]: "
labels: ["provider", "enhancement"]
projects: ["fastenhealth/fasten-onprem"]
assignees:
  - AnalogJ
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new Provider.
        
        Before you submit this request, please make sure that you've searched the existing issues to see if your provider has already been requested.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: provider-name
    attributes:
      label: Provider/Institution Name
      description: What is the name of this Institution?
      placeholder: ex. Humana/Kaiser/John Hopkins
    validations:
      required: true
  - type: input
    id: provider-website
    attributes:
      label: Provider/Institution Website
      description: Please share a link to the provider's website.
      placeholder: ex. https://www.humana.com/
    validations:
      required: true
  - type: input
    id: provider-website
    attributes:
      label: Provider/Institution Website
      description: Please share a link to the provider's website.
      placeholder: ex. https://www.humana.com/
    validations:
      required: true
  - type: input
    id: provider-ehr
    attributes:
      label: Provider EHR Platform
      description: If you know the name of the EHR platform that this provider uses, please share it.
      placeholder: ex. Epic MyChart, Cerner, Allscripts, etc
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else we should know?
      description: Please share any additional information or links that you think would be helpful.
    validations:
      required: false

