name: CDN-Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/src/assets/sources/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        default: 'info'
        options:
          - info
          - warning
          - debug
env:
  SSH_DEPLOY_KEY: ${{ secrets.FASTENHEALTH_CDN_SSH_DEPLOY_KEY }}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      with:
        source-directory: 'frontend/src/assets/sources'
        destination-github-username: 'fastenhealth'
        destination-repository-name: 'cdn'
        target-directory: 'logos/sources'
        user-email: jason@thesparktree.com
        target-branch: main
